### PR TITLE
Redesign Ribbon

### PR DESCRIPTION
**Pull request by savance-ford**
:recycle:  

Ready to go

### CODE REVIEW

**Comment by ericanaughton** [comment]
a tiny bit of the word Contribute shows before hovering
image

**Comment by ericanaughton** [comment]
i think some feedback we got is to have the words Contribute Here! showing before you hover, because some people may not recognize the Github logo.

**Comment by ericanaughton** [comment]
Oh i just remembered you were not going to use this ribbon anymore. Maybe just throw a construction symbol up in the description, rather than a green symbol, so we all know it's not ready.

**Comment by ericanaughton** [comment]
this shadow is a bit dark
image

everything else looks great though :)

**Comment by ericanaughton** [comment]
how does it look if the icon and text is centered in the ribbon? it's a bit top heavy.

**Comment by savance-ford** [comment]
They are centered @ericanaughton

**Comment by ericanaughton** [comment]
what i mean is something like this..
image

**Comment by savance-ford** [comment]
oh..lol

**Comment by savance-ford** [comment]
ok

**Comment by kathyoleary** [comment]
:+1:   I like it better than the previous and it looks good, but I may not be the best for giving thumbs on this level of coding.  Others will catch more than I will.

**Comment by ericanaughton** [comment]
i really like the bold lettering for Contribute, and i like that you removed the italics and the word Here. The shadow is excellent! However i notice a tiny thing.  Let me know if you don't see it.
image

**Comment by savance-ford** [comment]
@ericanaughton  
box-shadow2
 FINALLY FOUND IT!!! :dizzy_face:

**Comment by ericanaughton** [comment]
good job :) :+1:

**Pull request merged**
