### PR TITLE
Updates URL links

### PR DESCRIPTION
**Pull request by kathyoleary**
:construction:  Nate and I worked on this.  I didn't get a chance to test it thoroughly yet, so I am listing it as under construction until I get a chance to make sure we did not inadvertently break a link.
- Check the links throughly throughout the site to make sure all are working correctly
-  Pull up each of the elements and the welcome file individually

### CODE REVIEW

**Comment by kathyoleary** [comment]
I didn't put it on this sprint for this week because I'm only here for a short time on wed before we're in code freeze.  If someone gets a chance to verify this before then, it can be done.

**Comment by ericanaughton** [comment]
@kathyoleary how is this coming along?

**Comment by kathyoleary** [comment]
OK,

Got the html removed off the ends.  Put removing the hashtag on a separate Issue/PR along with fixing the enter key not reliably refreshing the page. 

This part however with the html not on the end of each link works fine.

**Comment by kathyoleary** [comment]
:green_book: ready to get approved.

**Comment by bigtiger** [comment]
Merge conflicts, otherwise :+1:

**Comment by whazzmaster** [comment]
Is there a linter running in LMHT? I've seen quite a few whitespace changes in the last few PRs and some of them seem to be at odds.

**Comment by ericanaughton** [comment]
@whazzmaster no there is not. do you suggest a specific kind?

**Comment by whazzmaster** [comment]
[eslint](http://eslint.org/) is what we're using in other projects, for JS linting at least. We should probably add it to this project so there's more confidence on commit that there aren't little style errors here and there. I'll add an issue.

I'm :+1: on this PR.

**Comment by kathyoleary** [comment]
I used a code cleaner on one of my issues just because it could catch things I could not.  Verified all changes it did and learned some nifty stuff along the way.

**Comment by rylnd** [comment]
Looks like the merge conflicts were incorrectly resolved; this branch should not introduce changes to js/combobox.js or elements/link.html.

**Comment by kathyoleary** [comment]
We changed it so it wouldn't submit those, that did not work?

**Pull request merged**
