### PR TITLE
Welcome Section - English

### PR DESCRIPTION
**Pull request by kathyoleary**
:palm_tree: 

ready to go

### CODE REVIEW

**Comment by jremsik-gpsw** [comment]
Can we separate this into an English PR and a Spanish PR so that we can merge English?

**Comment by ericanaughton** [comment]
@kathyoleary do you need help doing that?

**Comment by kathyoleary** [comment]
Hadn't merged yet, so pulled the spanish translations out and this one will be my english PR and I'll add a separate spanish PR for the rest

**Comment by ericanaughton** [comment]
@kathyoleary make sure to edit the description of this PR (the to-do list still has Spanish tasks)

**Comment by kathyoleary** [comment]
It shouldn't, I edited the spanish tasks out

**Comment by ericanaughton** [comment]
@kathyoleary I'm going to start working on having the Welcome Section show by default when the page opens.

**Comment by jremsik-gpsw** [comment]
:+1:

**Comment by ericanaughton** [comment]
@bigtiger am i allowed to give the 2nd thumb up and merge it?

**Comment by jremsik-gpsw** [comment]
@ericanaughton Not if you significantly contributed.

**Comment by jremsik-gpsw** [comment]
@werbeckes @LipGlossary @itsthatguy ?

**Comment by missingdink** [comment]
:+1:

**Pull request merged**
