### PR TITLE
Restyle combobox

### PR DESCRIPTION
**Pull request by ericanaughton**
:tea: 
 ready to go 

In order to search for definitions/translations of HTML elements 
As a Spanish/English speaking HTML learner, 
I want to easily know how to use it by first glance.

Acceptance Criteria:
- The search tool is the main focus (bigger)
- The search tool works 
- The search tool looks like a search tool (magnifying glass icon)
- The search tool shows me every element at the click of a button
- Guidance is given ('Search for an element'), so I know I can type in the search tool
- Once I click the button, the entire list of elements should be visible, no matter where I scroll.
- The search tool is pleasing to the eye

Given an English/Spanish speaking HTML learner, 
When I go to lmht.github.io,
I understand that I can search for elements by typing or clicking a button to see all the elements.

### CODE REVIEW

**Comment by jremsik-gpsw** [comment]
:+1: Looks great!

**Comment by ericanaughton** [comment]
thanks @jremsik-gpsw ! i tried using the format you showed us, for the description. was that format supposed to be used for the issues or the PR's? or both?

**Comment by ericanaughton** [comment]
one thing i've noticed is that a Spanish speaker may not understand 'Search for an element'.  However, putting a translation there may look a bit cluttered. I'm hoping they'll just get the point, with the search icon.

**Comment by rylnd** [comment]
RE the translation: how about simply "Search/Buscar" for the placeholder text?

**Comment by ericanaughton** [comment]
@rylnd good idea

**Comment by missingdink** [comment]
:+1:

**Pull request merged**
