### PR TITLE
Changes header as screen reduces to new specs

### PR DESCRIPTION
**Pull request by kathyoleary**
🍏  This one is ready to go for thumb wars!  Thanks!

### CODE REVIEW

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/74 posted this for review

**Comment by rylnd** [comment]
Can you explain what you're trying to accomplish with this PR? Without knowing what the "new specs" are, I can't determine whether you're conforming to them.

**Comment by kathyoleary** [comment]
Originally we had changed the header to expand to two rows with the LMHT logo on the left, the contribute ribbon on the right and the search bar below and centered.  After reviewing it, Jim the client said he wanted to switch it and remove the contribute ribbon totally whenever the screen size went below 1140 px. Then move the LMHT logo to center.

**Comment by rylnd** [comment]
Functionally, 👍 , but there remains some cleanup.

If the horizontal ribbon is _never_ to be shown, it should not be hidden via CSS. Doing so leads to technical debt in the form of "dead code" that just ends up cluttering up the codebase. 

All references to it should instead be deleted: HTML, CSS, and JS.

**Comment by kathyoleary** [comment]
The contribute ribbon is never going to show when the screen is under 1140px, but above that it will be present.

**Comment by rylnd** [comment]
@kathyoleary true, but the one that is displayed is `a.ribbon-link`. The "dead" one that I'm referring to is a separate element, `a.horizontal-ribbon`.

**Comment by kathyoleary** [comment]
Cleaned up the code, good catch.  I also slightly modified the size of the search bar because I noticed it was hitting the logo when at full size.

**Comment by rylnd** [comment]
One note about that last commit: please try not to "sneak" tangential changes into a commit. Changing the max-width of the search bar in a commit that "cleans up code to remove horizontal ribbon" needlessly obfuscates the reasoning behind the change.

If a commit does two things, it should _at least_ describe both of those things. Ideally, it would be two commits. It's good of you to note the change on GitHub, but it's better to store it in git itself (via the commit message) so that we're not (necessarily) reliant upon GitHub. If you have any questions I'm more than happy to answer them.

**Comment by rylnd** [comment]
Commit issues aside, the code looks good to me. 👍

**Comment by ericanaughton** [comment]
👍  good job @kathyoleary !

**Pull request merged**
