### PR TITLE
Update translation for Welcome page

### PR DESCRIPTION
**Pull request by mostlybadfly**
@ericanaughton @kathyoleary This is my translation for the Welcome page.

### CODE REVIEW

**Comment by ericanaughton** [comment]
thanks @mostlybadfly !

**Comment by JenEEsquivel** [comment]
Thank you @mostlybadfly 
Edit:  @ericanaughton :+1: after change todav&iacute; to todav&iacute;a (<--there should be the letter a after the unicode for accent on i)

**Comment by ericanaughton** [comment]
@bigtiger should we just merge this for now, so we don't have that blank space?

**Comment by bigtiger** [comment]
:+1:

**Comment by mostlybadfly** [comment]
No problem, happy to help!

**Pull request merged**
